# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46f02bb2905f23d33b854527ac5242c4787d1a389e8c342a5cb65c6d92cc783781feb8dd84a2e6d2771f37c7c68b0449ebe0499ee3703239c3b159775dde6e65

test:
  secret_key_base: 455235891b51574a96f64f340e5da66812894250a8ba8a8ed20552d47831313b95c6200cf6c468d3ce79a1a5f83a85e5e7a3e228ee87f5919c226ef8ce675ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
